# Generated by Django 4.0.6 on 2022-08-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statictracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Username',
        ),
    ]
