# Generated by Django 4.0.6 on 2022-08-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statictracking', '0002_rename_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ManyToManyField(related_name='user_property', to='statictracking.username'),
        ),
    ]
